server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/eventtix}
    username: ${DB_USER:auth_user}
    password: ${DB_PASSWORD:auth_pass}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: auth_schema
  flyway:
    schemas: auth_schema
    default-schema: auth_schema

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
