-- event_title ve unit_price sipariş anında kopyalanır (denormalizasyon).
CREATE TABLE orders (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT         NOT NULL,
    event_id       BIGINT         NOT NULL,
    event_title    VARCHAR(255)   NOT NULL,
    quantity       INT            NOT NULL CHECK (quantity > 0),
    unit_price     NUMERIC(10, 2) NOT NULL,
    total_price    NUMERIC(10, 2) NOT NULL,
    status         VARCHAR(20)    NOT NULL,
    failure_reason VARCHAR(20),
    created_at     TIMESTAMPTZ    NOT NULL,
    updated_at     TIMESTAMPTZ    NOT NULL
);

CREATE INDEX idx_orders_user ON orders (user_id);
