CREATE TABLE tickets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT       NOT NULL,
    seq_no      INT          NOT NULL,
    user_id     BIGINT       NOT NULL,
    event_id    BIGINT       NOT NULL,
    ticket_code VARCHAR(36)  NOT NULL UNIQUE,
    qr_path     VARCHAR(500) NOT NULL,
    pdf_path    VARCHAR(500) NOT NULL,
    used        BOOLEAN      NOT NULL DEFAULT false,
    created_at  TIMESTAMPTZ  NOT NULL
);

-- Idempotency: aynı sipariş için biletler iki kez üretilmez.
CREATE UNIQUE INDEX uq_tickets_order ON tickets (order_id, seq_no);

CREATE INDEX idx_tickets_user ON tickets (user_id);
