server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/eventtix}
    username: ${DB_USER:order_user}
    password: ${DB_PASSWORD:order_pass}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: order_schema
  flyway:
    schemas: order_schema
    default-schema: order_schema
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USER:eventtix}
    password: ${RABBITMQ_PASSWORD:eventtix}
    listener:
      simple:
        # 3 deneme başarısızsa mesaj requeue edilmez, x-dead-letter-exchange ile DLQ'ya düşer.
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1s

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
