CREATE TABLE events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255)   NOT NULL,
    description TEXT,
    venue       VARCHAR(255)   NOT NULL,
    city        VARCHAR(100)   NOT NULL,
    event_date  TIMESTAMPTZ    NOT NULL,
    price       NUMERIC(10, 2) NOT NULL,
    total_quota INT            NOT NULL,
    sold_count  INT            NOT NULL DEFAULT 0,
    image_url   VARCHAR(500),
    created_at  TIMESTAMPTZ    NOT NULL,
    CONSTRAINT chk_events_sold_count CHECK (sold_count >= 0 AND sold_count <= total_quota)
);

CREATE INDEX idx_events_city_date ON events (city, event_date);

-- Idempotency: aynı sipariş için kontenjan iki kez ayrılmaz.
CREATE TABLE quota_reservations (
    order_id   BIGINT PRIMARY KEY,
    event_id   BIGINT      NOT NULL REFERENCES events (id),
    quantity   INT         NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);
